'use client';

import React from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, History } from 'lucide-react';
import { useLicenseDetailQuery } from '@/hooks/useLicenses';
import LicenseDetailCard from '@/components/license/LicenseDetailCard';
import ActionBadge from '@/components/audit/ActionBadge';
import { format } from 'date-fns';

export default function LicenseDetailPage() {
  const params = useParams();
  const router = useRouter();
  const key = params.key as string;

  const { data, isLoading, isError, error } = useLicenseDetailQuery(key);

  if (isError) {
    return (
      <div className="space-y-4">
        <button
          onClick={() => router.back()}
          className="flat-btn flat-btn-secondary gap-2 text-xs uppercase tracking-wider py-1.5"
        >
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
        <div className="p-6 flat-card border border-rose-500/20 bg-rose-500/5 text-rose-400">
          <h3 className="font-bold text-lg">Failed to retrieve license details</h3>
          <p className="text-sm mt-1">{error?.message || 'An unexpected error occurred.'}</p>
        </div>
      </div>
    );
  }

  // Loading skeleton state
  if (isLoading || !data) {
    return (
      <div className="space-y-6">
        <div className="h-9 w-24 bg-zinc-800 rounded animate-pulse" />
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 space-y-6">
            <div className="h-64 bg-card flat-card animate-pulse" />
            <div className="h-40 bg-card flat-card animate-pulse" />
          </div>
          <div className="space-y-6">
            <div className="h-32 bg-card flat-card animate-pulse" />
            <div className="h-48 bg-card flat-card animate-pulse" />
          </div>
        </div>
      </div>
    );
  }

  const { license, auditLogs } = data;

  interface AuditLogDetails {
    ownerTag?: string;
    maxIps?: number;
    reason?: string;
    oldOwnerId?: string;
    newOwnerTag?: string;
    newOwnerId?: string;
    hwidReset?: boolean;
  }

  const getActionDescription = (action: string, details: AuditLogDetails) => {
    switch (action.toLowerCase()) {
      case 'generate':
        return `License generated by actor ${details.ownerTag || 'system'} with max ${details.maxIps} allowed IPs.`;
      case 'suspend':
        return `License suspended. Reason: ${details.reason || 'No reason provided.'}`;
      case 'revoke':
        return `License permanently revoked. Reason: ${details.reason || 'No reason provided.'}`;
      case 'reactivate':
        return `License reactivated by administrator. Reason: ${details.reason || 'No reason provided.'}`;
      case 'transfer':
        return `License ownership transferred from ${details.oldOwnerId || 'previous'} to ${details.newOwnerTag || 'new owner'} (${details.newOwnerId}).`;
      case 'update_ips':
        if (details.hwidReset) {
          return `Whitelisted IPs modified. HWID lock was reset.`;
        }
        return `Whitelisted IPs updated.`;
      default:
        return details.reason || 'Action recorded in audit log';
    }
  };

  return (
    <div className="space-y-6">
      {/* Back Button */}
      <div>
        <button
          onClick={() => router.back()}
          className="flat-btn flat-btn-secondary gap-2 text-xs uppercase tracking-wider py-1.5"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Licenses
        </button>
      </div>

      {/* Core metadata card */}
      <LicenseDetailCard license={license} />

      {/* Audit timeline */}
      <div className="flat-card p-6 bg-card space-y-6">
        <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-wider border-b border-border pb-2 flex items-center gap-2">
          <History className="w-4 h-4 text-zinc-500" />
          Status History & Audit Timeline
        </h4>

        {auditLogs.length === 0 ? (
          <p className="text-xs italic text-zinc-600">No audit logs recorded for this license key</p>
        ) : (
          <div className="relative pl-6 space-y-6 border-l border-border/80 ml-3 pt-2">
            {auditLogs.map((log) => (
              <div key={log._id} className="relative">
                {/* Timeline bullet */}
                <div className="absolute -left-[30px] top-1.5 w-3.5 h-3.5 rounded-full bg-zinc-950 border-2 border-primary" />

                <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
                  <div className="flex items-center gap-3">
                    <ActionBadge action={log.action} />
                    <span className="text-zinc-500 text-xs">
                      Actor: <span className="font-mono text-zinc-400">{log.actorId}</span>
                    </span>
                    {log.ip && (
                      <span className="text-zinc-600 text-xs font-mono">({log.ip})</span>
                    )}
                  </div>
                  <span className="text-xxs font-mono text-zinc-500">
                    {format(new Date(log.timestamp), 'yyyy-MM-dd HH:mm:ss')}
                  </span>
                </div>

                <p className="mt-1.5 text-xs text-zinc-400 font-medium">
                  {getActionDescription(log.action, log.details)}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
